database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
application:
  port: 8000
email_client:
  base_url: localhost
  sender_email: "selfishtoaster@gmail.com"
  timeout_milliseconds: 10000
  authorization_token: "my-secret-token"